name: test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    # https://mcr.microsoft.com/en-us/artifact/mar/playwright/about
    container: mcr.microsoft.com/playwright@sha256:146d046a8d79a1b3a87596c4457b0b1c47f811bf4fc2cc1b99e873ae7f1cbbbd # v1.51.1-noble
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: cat index.html
      - run: rm -rf node_modules/.cache/ms-playwright
      - run: npm test
      # upload everytime
      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#always
      - if: ${{ !cancelled() }}
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          if-no-files-found: error
          path: playwright-report
          retention-days: 7
