name: update snapshot

on:
  - workflow_dispatch

jobs:
  take-snapshot:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.51.1-noble
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: npm run test:update-snapshots
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: __snapshots__
          path: __snapshots__
          include-hidden-files: true
          overwrite: true
  update-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: __snapshots__
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '<41898282+github-actions[bot]@users.noreply.github.com>'
      - run: |
          git checkout -b chore/update-snapshots
          git add .
          git commit -m "chore: update snapshots"
          git push origin +chore/update-snapshots
      - run: >
          gh pr create
            --title "chore: update snapshots"
            --body "This PR updates snapshots"
            --base main
            --head chore/update-snapshots
